version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pd_database'
    expose:
      - 5432
    ports:
      - '5433:5432'

  api:
    image: node:18-alpine
    command: [ 'npm', 'run', 'dev' ] # TODO: adjust to add prisma migrate
    depends_on:
      - db

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "4500:8080"
    container_name: docs
    volumes:
      - ./docs:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yaml
