version: '3'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pd_database'
    expose:
      - 5432
    ports:
      - '5433:5432'

  api:
    image: node:18-alpine
    command: ['npm', 'run', 'dev'] # TODO: adjust to add prisma migrate
    depends_on:
      - db
