version: "3"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pd_database"
    expose:
      - 5432
    ports:
      - "5432:5432"

  api:
    image: node:18-alpine
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma db seed && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - ${SERVER_PORT:-4000}:${SERVER_PORT:-4000}

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "4500:8080"
    container_name: docs
    volumes:
      - ./docs:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yaml
