openapi: 3.1.0

info:
  title: Progresso Docente API
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: development server

paths:
  /login:
    $ref: "./auth/login.yaml"

components:
  schemas:
    $ref: "./schemas.yaml"
